packages:
  - "packages/*"

allowBuilds:
  argon2: true
  cpu-features: true
  esbuild: true
  sharp: true
  ssh2: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@arkstack/*'
  - '@h3ravel/*'
  - '@kanun-hq/*'
  - '@resora/*'
  - '@arkormx/*'
  - '@pictwo/*'
  - clear-router
  - arkormx
  - resora
  - kanun